accelerator: null
accumulate_grad_batches: null
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: null
attn_head: 16
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: null
check_val_every_n_epoch: 1
checkpoint_callback: null
dataloader_workers: 16
datasets_name: Sports
datasets_path_test:
- ../data/Sports/imgs_seq_5_test.pickle
datasets_path_train:
- ../data/Sports/imgs_seq_5_train.pickle
datasets_path_val:
- ../data/Sports/imgs_seq_5_val.pickle
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
dropout: 0.8
emb_img_model: img_emb_clip_vit_large_patch14.pt
emb_img_train: true
emb_title_model: title_emb_clip_vit_large_patch14_len10.pt
emb_title_train: true
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
every_n_epochs: 1
every_n_train_steps: null
fast_dev_run: false
filename: model-{epoch:02d}-{step:d}
flush_logs_every_n_steps: null
fuse_gl_flag: true
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
hidden_size: 768
info: Liner pred, emb nofinetune, fuse global local seq rep
ipus: null
learning_rate: 0.0005
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
load_ckpt_path: ../../ckpt/temp/
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr_decay_ratio: 1.0
lr_decay_steps: 0
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_learning_rate: 5.0e-05
min_steps: null
mode: max
model_state_save: true
monitor: Recall@10
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_blocks: 1
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 8
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
pretrain_flag: false
process_position: 0
profiler: null
progress_bar_refresh_rate: null
random_seed: 512
raw_file_type: json
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
sampler_type: random
save_ckpt_path: ../../ckpt/temp/
save_last: true
save_on_train_epoch_end: null
save_top_k: 100
save_weights_only: false
scheduler_type: cosine
seq_len: 10
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
test_batchsize: 128
test_datasets_field: test
test_file: null
tpu_cores: null
track_grad_norm: -1
train_batchsize: 128
train_datasets_field: train
train_file: null
val_batchsize: 128
val_check_interval: null
val_datasets_field: val
val_file: null
warmup_ratio: 0.1
warmup_steps: 0
weight_decay: 0.1
weights_save_path: null
weights_summary: top
